[project]
name = "quizzapp"
version = "0.1.0"
description = "Quizz website to learn Django"
readme = "README.md"
authors = [
    { name = "ESHcker", email = "274484520+ESHcker@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
]

[project.scripts]
quizzapp = "quizzapp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
